development:
  adapter: postgresql
  encoding: unicode
  database: development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: production
  pool: 5